language: go

go:
    - 1.6

install:
    - go get github.com/nexustix/boilerplate
    - go get github.com/nxReplicator/nxReplicatorCommon

before_deploy:
    - env GOOS=linux GOARCH=amd64 go build -o ${HOME}/dist/linux64/nxatomize github.com/nxReplicator/nxatomize
    - env GOOS=windows GOARCH=amd64 go build -o ${HOME}/dist/windows64/nxatomize.exe github.com/nxReplicator/nxatomize
    - chmod +x ${HOME}/dist/linux64/nxatomize

deploy:
    provider: releases
    api_key:
        secure: G5zi9i0ie3r+R1dUuEH7Plv7Kef8yxxPjBP1heVj2cp8Q4mEvEi7GIV/Dgf1TUvkG5XUlmDzGewwGvSAindskUrTpJCCGb0p2ah8bGrL512h4dZo2ZDRAiK+cIqps2zg4aD7AP9es/il7mT5yP3KTOkjoSE2vqPNZQW/TpAcHqOThshkzdLvu4Iarh5N3aIcREkeClfVi5Uj0OYSBS/ZRXFPEGTmjvsphALQiXnr3GABIr6xQKHd7WPAf1B06w34C7OZx6LkHngcPfnbkdhYW8z/ObxxD0cN7fmN6qSex7ZrvyaCWkF6NVvovtoH5XPOhVYMt/sq6xOq4d++WULzt8cAo2fwoL48RsxZSEjtowu0cSVFkXZSbMnFw+hqQg8uCM3LQBAFdhvqCtGxZPjyhH2Cvffnmi4xquCCcnpI27eF/n6xpLQro5xNfoZ+/ealY6Zj4TQtr3HpBhVk1ru8W818L64e3h6jc+j5Vg/2AJgp/lW7CeH/E6I9N+uJPad+yXhfdxVP0kXLrEHx/tyfkAFaucseKyWrjXT9CCCXA5l6S5gEFhXwH1ZkNkGMQagsnG5W8iAxL2godNWPIUmX01sDfSxBC8k+dVQq1BUwgfMXg3PhJ4GPey2AKh4PtEEaN90QckmY+uMrst0rNB8mQxPZrXAyTneU++TIxmsZmVQ=
    file:
        - "${HOME}/dist/windows64/nxatomize.exe"
        - "${HOME}/dist/linux64/nxatomize"
    skip_cleanup: true
    on:
        tags: true
